# Generated by Django 3.0.4 on 2020-03-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fenouil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=80)),
                ('nom', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=150)),
                ('ville', models.CharField(max_length=50)),
                ('pays', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('code_postal', models.IntegerField()),
                ('commentaires', models.CharField(max_length=300)),
            ],
        ),
    ]
