# Generated by Django 2.1.5 on 2020-04-20 13:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fenouil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anomalie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_commande', models.CharField(max_length=50)),
                ('statut', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(default=None, verbose_name='Date de publication')),
            ],
        ),
        migrations.CreateModel(
            name='Envoi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=8)),
                ('num', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Individu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=80)),
                ('adresse', models.CharField(max_length=150)),
                ('num', models.IntegerField(default=0)),
                ('ville', models.CharField(max_length=50)),
                ('code_postal', models.IntegerField()),
                ('pays', models.CharField(max_length=50)),
                ('nombre_de_commandes', models.IntegerField(default=0)),
                ('somme_totale_depensee', models.FloatField(default=0)),
                ('commentaires', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('categorie_soc', models.CharField(max_length=50)),
                ('caracteristique_comm', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', ckeditor.fields.RichTextField(verbose_name='')),
            ],
        ),
    ]
