# Generated by Django 2.1.5 on 2020-04-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fenouil', '0003_auto_20200420_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='CibleRoutage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie_socio_professionelle', models.CharField(max_length=50)),
                ('age_minimum', models.IntegerField()),
                ('age_maximum', models.IntegerField()),
                ('departement', models.CharField(max_length=50)),
                ('individus_selectionnes', models.CharField(max_length=100)),
                ('type_canal', models.CharField(max_length=10)),
                ('type_papier', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('titre', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('articles_selec', models.CharField(max_length=300)),
            ],
        ),
    ]
