# Generated by Django 3.0.4 on 2020-04-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fenouil', '0003_auto_20200401_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='commentaires',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
