# Generated by Django 2.1.5 on 2020-04-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fenouil', '0004_cibleroutage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cibleroutage',
            name='statut',
            field=models.BooleanField(default=False),
        ),
    ]
