# Generated by Django 3.0.4 on 2020-04-01 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fenouil', '0005_auto_20200401_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='commentaires',
        ),
    ]
