# Generated by Django 3.0.4 on 2020-04-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fenouil', '0006_remove_client_commentaires'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='commentaires',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
