# Generated by Django 2.1.5 on 2020-05-02 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fenouil', '0007_auto_20200502_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcommande',
            name='item_existant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='fenouil.Item'),
        ),
    ]
