# Generated by Django 3.0.4 on 2020-04-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fenouil', '0007_client_commentaires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='somme_totale_depensee',
            field=models.FloatField(default=0),
        ),
    ]
