# Generated by Django 2.1.5 on 2020-05-05 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fenouil', '0007_auto_20200505_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envoi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_envoi', models.DateTimeField(default=None, verbose_name="Date d'envoi")),
            ],
        ),
        migrations.AlterField(
            model_name='itemcommande',
            name='item_existant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='fenouil.Item'),
        ),
    ]
