# Generated by Django 3.0.4 on 2020-04-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fenouil', '0008_auto_20200401_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
