# Generated by Django 2.1.5 on 2020-05-02 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fenouil', '0008_auto_20200502_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandecartebancaire',
            name='articles',
        ),
        migrations.AddField(
            model_name='commandecartebancaire',
            name='articles',
            field=models.ManyToManyField(to='fenouil.ItemCommande'),
        ),
        migrations.RemoveField(
            model_name='commandecheque',
            name='articles',
        ),
        migrations.AddField(
            model_name='commandecheque',
            name='articles',
            field=models.ManyToManyField(to='fenouil.ItemCommande'),
        ),
        migrations.AlterField(
            model_name='itemcommande',
            name='item_existant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='fenouil.Item'),
        ),
    ]
