# Generated by Django 2.1.5 on 2020-05-03 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fenouil', '0009_auto_20200502_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commandecartebancaire',
            old_name='valide',
            new_name='carte_valide',
        ),
        migrations.AlterField(
            model_name='itemcommande',
            name='item_existant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='fenouil.Item'),
        ),
    ]
