# Generated by Django 2.1.5 on 2020-04-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fenouil', '0009_client_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envoi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=8)),
                ('num', models.CharField(max_length=100)),
            ],
        ),
    ]
