# Generated by Django 2.1.5 on 2020-04-15 16:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fenouil', '0010_envoi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
