# Generated by Django 2.1.5 on 2020-05-03 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fenouil', '0010_auto_20200503_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandecartebancaire',
            name='valide',
            field=models.CharField(default='ok', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commandecheque',
            name='valide',
            field=models.CharField(default='ok', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemcommande',
            name='item_existant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='fenouil.Item'),
        ),
    ]
