# Generated by Django 2.1.5 on 2020-05-07 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fenouil', '0010_auto_20200507_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcommande',
            name='item_existant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='fenouil.Item'),
        ),
    ]
