# Generated by Django 2.1.5 on 2020-04-15 20:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fenouil', '0011_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='contenu',
            field=ckeditor.fields.RichTextField(verbose_name=''),
        ),
    ]
