# Generated by Django 2.1.5 on 2020-04-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fenouil', '0012_auto_20200415_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anomalie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_commande', models.CharField(max_length=50)),
                ('statut', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
