# Generated by Django 2.1.5 on 2020-05-09 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fenouil', '0013_auto_20200507_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='individu',
            name='date_passage_client',
            field=models.DateTimeField(default=None, verbose_name='Date client'),
        ),
        migrations.AlterField(
            model_name='itemcommande',
            name='item_existant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='fenouil.Item'),
        ),
    ]
