# Generated by Django 2.1.5 on 2020-04-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fenouil', '0014_anomalie_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalie',
            name='statut_html',
            field=models.CharField(default='info', max_length=30),
        ),
    ]
