# Generated by Django 2.1.5 on 2020-04-18 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fenouil', '0015_anomalie_statut_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anomalie',
            name='statut_html',
        ),
    ]
